### ISSUE TITLE
Will 0.11 come?

### ISSUE THREAD

**Issue by thigg** [prosody/homebrew-prosody#14]
If so, when?

**Comment by pd888** [comment]
Bumping this - current homebrew version is quite old.
Thanks

**Comment by lonllua** [comment]
hope update it. Thanks!

**Comment by Zash** [comment]
Uncertain. We don't currently have anyone who maintains this. [Help would be welcome](https://prosody.im/discuss)

**Comment by Zash** [comment]
Please test
