### ISSUE TITLE
SHA256

### ISSUE THREAD

**Issue by DomT4** [prosody/homebrew-prosody#7]
Please update your formula to use SHA256.

We've been trying to deprecate SHA1 since [March](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Checksum_Deprecation.md), please try to watch for things like that as a tap author, we don't do it extremely often but leaving behind old checksums & syntax choices allows us to drop ancient code in the core & the end result is more pleasant for everyone. Appreciated!

```
https://prosody.im/tmp/0.9.7/prosody-0.9.7.tar.gz
dd4b99b39976442055898c933c013598e558beed11d7795d76ffc0f1a87e2e00
```

**Comment by zeen** [comment]
Fixed in https://github.com/prosody/homebrew-prosody/pull/9, thanks for your efforts @DomT4!

**Comment by DomT4** [comment]
Thanks for fixing that @zeen ❤️.
